organisit/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/help'

  resources :classrooms
  resources :coursesessions
  resources :courses
  resources :enrolments
  delete '/enrolments/:id/delete', to: 'enrolments#destroy', as: :enrolment_delete

  devise_for :users

  root to: "static_pages#home"

  resources :users, only: [:index, :show, :edit, :update] 

end

organisit/app/models/classroom.rb
class Classroom < ActiveRecord::Base
  has_many :courses




end

organisit/app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  def index
    @classrooms = Classroom.all
  end

  def show
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end

  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.save
    redirect_to(classrooms_path)
  end

  def update
    @classroom.update(classroom_params)
    redirect_to(classrooms_path)
  end

  def destroy
    @classroom.destroy
    redirect_to(classrooms_path)
  end

  private
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def classroom_params
      params.require(:classroom).permit(:name, :capacity, :city, :address)
    end
end

organisit/app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

organisit/app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

organisit/app/views/classrooms/edit.html.erb
<h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

organisit/app/views/classrooms/index.html.erb
<p><em>"Cool, cool, cool" – Michael Pavling</em></p><br>
<h2>Schedule for <%= Date.today.strftime("%b %-d, %Y") %></h2>

<ul>
<% Course.course_today.each do |course| %>
  <li><%= course.title %> (<%= course.timesofday_for_course.downcase.strip.singularize %>)<br>
  Classroom: <%= Classroom.where(id: course.classroom_id).first.name %><br><br><%= link_to 'View course details', course %></li><br>
<% end %><br><br>
</ul>

<h3>Manage classrooms</h1>
  <ul>
    <% @classrooms.each do |classroom| %>
    <li>
      <%= classroom.name %><br>
      <%= classroom.address %><br>
      <%= classroom.city %><br>
      Capacity: <%= classroom.capacity %><br>
    </li><br>
    <%= link_to 'Edit name', edit_classroom_path(classroom) %> |
    <%= link_to 'Remove', classroom, method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
    <% end %>
  </ul>

<%= link_to 'New Classroom', new_classroom_path %>

organisit/app/views/classrooms/new.html.erb
<h1>New classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

organisit/app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classroom.name %>
</p>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>