organisit/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/help'

  resources :classrooms
  resources :coursesessions
  resources :courses
  resources :enrolments
  delete '/enrolments/:id/delete', to: 'enrolments#destroy', as: :enrolment_delete

  devise_for :users

  root to: "static_pages#home"

  resources :users, only: [:index, :show, :edit, :update] 

end

organisit/app/views/layouts/_publicnav.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', static_pages_home_path  %></li>
    <li><%= link_to 'About', static_pages_about_path%></li>
    <li><%= link_to 'Contact', static_pages_contact_path%></li>
    <li><%= link_to 'Help', static_pages_help_path%></li>
  </ul>
</nav>

organisit/app/views/layouts/_staffnav.html.erb
<nav>
  <ul>
    <li><%= link_to 'Courses', courses_path %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Enrolment', enrolments_path %></li>
    <li><%= link_to 'Classrooms', classrooms_path %></li>
  </ul>
</nav>
<br>
<hr>
<br>

organisit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Organisit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header><h1>Michael's School of Code</h1></header>
  <div class='login'>
    <% if current_user %>
      <%= current_user.email %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
  </div>



  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render partial: "layouts/publicnav" unless can? :index, Course %>
  <%= render partial: "layouts/staffnav" if can? :index, Course %>

<%= yield %>

</body>
</html>