organisit/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/help'

  resources :classrooms
  resources :coursesessions
  resources :courses
  resources :enrolments
  delete '/enrolments/:id/delete', to: 'enrolments#destroy', as: :enrolment_delete

  devise_for :users

  root to: "static_pages#home"

  resources :users, only: [:index, :show, :edit, :update] 

end

organisit/app/models/enrolment.rb
class Enrolment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course

#1
  scope :instructors, -> { where(position: 'instructor') }


end

organisit/app/controllers/enrolments_controller.rb
class EnrolmentsController < ApplicationController
  before_action :set_enrolment, only: [:show, :edit, :update, :destroy]

  def index
    @enrolments = Enrolment.all
  end

  def edit
  end

  def new
    @enrolment = Enrolment.new
  end

  def update
    @enrolment.update(enrolment_params)
    redirect_to(enrolments_path)
  end

  def create
    @enrolment = Enrolment.new(enrolment_params)
    @enrolment.position = "student"
    @enrolment.save
    redirect_to(enrolments_path)
  end

  def destroy
    @enrolment.destroy
    redirect_to(enrolments_path)
  end

  private
    def set_enrolment
      @enrolment = Enrolment.find(params[:id])
    end

    def enrolment_params
      params.require(:enrolment).permit(:course_id, :user_id, :postion)
    end
end

organisit/app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

organisit/app/views/enrolments/_form.html.erb
<h3>Enrol a student</h3>
<%= form_for(@enrolment) do |f| %>
  <% if @enrolment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrolment.errors.count, "error") %> prohibited this enrolment from being saved:</h2>

      <ul>
      <% @enrolment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id, 'Courses' %><br>
    <%= f.collection_select(:course_id, Course.all, :id, :title, prompt: true) %><br><br>
    <%= f.label :student_id, 'Students' %><br>
    <%= f.collection_select(:user_id, User.all, :id, :name, prompt: true) %><br><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>

organisit/app/views/enrolments/edit.html.erb
edit.html.erb

organisit/app/views/enrolments/index.html.erb
<p><em>"There's cake? WHERE?!" – Michael Pavling</em></p><br>
<h2>Enrolled students</h2><br>
<%= link_to 'New Enrolment', new_enrolment_path %>
  <% Course.with_students.each do |course| %>
    <h3><%= course.title %></h3>
    <p>Maximum enrolment: <%= course.max_no_of_students %> students</p>
    <ol>
    <% course.student_enrolments.each do |enrolment| %>
      <li><p><%= enrolment.user.try :name %></p>
      <%= link_to 'Remove', enrolment_delete_path(enrolment), method: :delete, data: { confirm: 'Oh is that how it is? Whatever...' } if can? :destroy, enrolment %></li>
    <% end %>
    </ol>
    <%#= link_to 'Edit enrolments', edit_enrolment_path(enrolment)  if can? :edit, enrolment %> 
  <% end %>

<br><br>
<%= link_to 'New Enrolment', new_enrolment_path %>

organisit/app/views/enrolments/new.html.erb
<%= render 'form' %>